import React from 'react';
import { Link } from 'react-router-dom';

export const TermsPage: React.FC = () => {
  const lastUpdated = "December 5, 2024";

  return (
    <div className="min-h-screen pt-32 pb-24 container mx-auto px-6">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-serif text-brand-darkest mb-4">Terms of Service</h1>
          <p className="text-gray-500">Last updated: {lastUpdated}</p>
        </div>

        <div className="prose prose-lg prose-headings:font-serif prose-headings:text-brand-darkest prose-p:text-gray-700 prose-a:text-brand-clay max-w-none">

          <p>
            Welcome to Montessori Milestones. By accessing or using our website at montessorimilestones.com, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our website.
          </p>

          <h2>Affiliate Disclosure</h2>
          <div className="bg-brand-paper p-6 rounded-xl my-6 not-prose">
            <p className="text-brand-darkest font-medium mb-2">
              <strong>Important:</strong> Montessori Milestones is a participant in affiliate programs, including the Impact.com affiliate network.
            </p>
            <p className="text-gray-700 text-sm">
              This means that when you click on product links on our website and make a purchase, we may earn a commission at no additional cost to you. We only recommend products we genuinely believe in and that align with Montessori principles. Our affiliate relationships do not influence our editorial content or product recommendations.
            </p>
          </div>

          <h3>FTC Compliance</h3>
          <p>
            In accordance with the Federal Trade Commission's guidelines on endorsements and testimonials, we disclose that:
          </p>
          <ul>
            <li>We may receive compensation for products purchased through links on this site</li>
            <li>We have affiliate relationships with brands including Lovevery</li>
            <li>Product reviews and recommendations reflect our honest opinions</li>
            <li>Compensation does not influence our editorial integrity</li>
          </ul>

          <h2>Use of Website</h2>
          <p>You agree to use this website only for lawful purposes and in a way that does not:</p>
          <ul>
            <li>Infringe the rights of others</li>
            <li>Restrict or inhibit anyone else's use of the website</li>
            <li>Violate any applicable laws or regulations</li>
            <li>Transmit any harmful, offensive, or illegal content</li>
            <li>Attempt to gain unauthorized access to our systems</li>
          </ul>

          <h2>AI Chatbot Terms</h2>
          <p>
            Our website includes an AI-powered assistant named "Maria" that provides Montessori parenting guidance and product recommendations. By using this feature, you acknowledge that:
          </p>
          <ul>
            <li>Responses are generated by artificial intelligence and may not always be accurate</li>
            <li>The chatbot provides general guidance, not professional child development advice</li>
            <li>Product recommendations include affiliate links (see Affiliate Disclosure above)</li>
            <li>You should consult qualified professionals for specific child development concerns</li>
            <li>We are not liable for decisions made based on chatbot recommendations</li>
          </ul>

          <h2>Intellectual Property</h2>
          <p>
            All content on this website, including text, images, graphics, logos, and software, is the property of Montessori Milestones or our content suppliers and is protected by copyright and trademark laws. You may not:
          </p>
          <ul>
            <li>Reproduce, distribute, or republish our content without permission</li>
            <li>Use our trademarks or branding without written consent</li>
            <li>Create derivative works based on our content</li>
          </ul>
          <p>
            You may share links to our content and quote brief excerpts with attribution.
          </p>

          <h2>User-Generated Content</h2>
          <p>
            If you submit content to our website (such as comments or forum posts, when available), you grant us a non-exclusive, royalty-free license to use, display, and distribute that content. You are responsible for ensuring your submissions do not violate any third-party rights.
          </p>

          <h2>Product Information</h2>
          <p>
            We strive to provide accurate product information, but we do not guarantee that product descriptions, pricing, or availability information is accurate, complete, or current. Product information is provided by third-party retailers and manufacturers.
          </p>

          <h2>Disclaimer of Warranties</h2>
          <p>
            This website and its content are provided "as is" without warranties of any kind, either express or implied. We do not warrant that:
          </p>
          <ul>
            <li>The website will be uninterrupted or error-free</li>
            <li>Defects will be corrected</li>
            <li>The website is free of viruses or harmful components</li>
            <li>Information provided is complete or accurate</li>
          </ul>

          <h2>Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, Montessori Milestones shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from:
          </p>
          <ul>
            <li>Your use of or inability to use the website</li>
            <li>Any products purchased through affiliate links</li>
            <li>Reliance on information provided on the website or by our AI chatbot</li>
            <li>Unauthorized access to your data</li>
          </ul>

          <h2>Parenting & Educational Disclaimer</h2>
          <p>
            The content on Montessori Milestones is for informational and educational purposes only. It is not intended to replace professional advice from pediatricians, child psychologists, or certified Montessori educators. Every child is unique, and what works for one family may not work for another.
          </p>

          <h2>External Links</h2>
          <p>
            Our website contains links to third-party websites, including affiliate partner sites. We are not responsible for the content, privacy practices, or terms of service of these external sites. Clicking on external links is at your own risk.
          </p>

          <h2>Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Montessori Milestones, its owners, employees, and affiliates from any claims, damages, or expenses arising from your use of the website or violation of these terms.
          </p>

          <h2>Governing Law</h2>
          <p>
            These Terms of Service are governed by the laws of the United States and the State of Pennsylvania. Any disputes arising from these terms or your use of the website shall be resolved in the courts of the Commonwealth of Pennsylvania.
          </p>

          <h2>Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms of Service at any time. Changes will be effective immediately upon posting to the website. Your continued use of the website after changes constitutes acceptance of the modified terms.
          </p>

          <h2>Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you have questions about these Terms of Service, please contact us at:
          </p>
          <p>
            <strong>Email:</strong> revella@montessorimilestones.com
          </p>

          <div className="mt-12 pt-8 border-t border-brand-paper">
            <p className="text-sm text-gray-500">
              See also: <Link to="/privacy">Privacy Policy</Link>
            </p>
          </div>

        </div>
      </div>
    </div>
  );
};
